#!/bin/sh
cd ../Obj48

export CC="gcc -I../C -s -Os -g0 -fvisibility=hidden -fomit-frame-pointer -finline-small-functions -fno-exceptions -fno-unwind-tables -fno-asynchronous-unwind-tables -ffunction-sections -Wl,--gc-sections -Wfatal-errors"
export AR="ar -rc libCPfront.a"
if [ -f "libCPfront.a" ]; then rm "libCPfront.a"; fi

## Kernel
$CC -c ../C/SYSTEM.c Types.c Log.c Kernel.c Files.c HostFiles.c Console.c HostLang.c HostConsole.c BbCmdLine.c BbCmdLineLinux.c Dialog.c
if [ $? != 0 ]; then exit 1; fi
$AR SYSTEM.o Types.o Log.o Kernel.o Files.o HostFiles.o Console.o HostLang.o HostConsole.o BbCmdLine.o BbCmdLineLinux.o Dialog.o

## Main
$CC BbOdcToText.c -o ../odc2txt -L. -lCPfront -ldl
if [ $? != 0 ]; then exit 1; fi
